# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160416_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
